# Generated by Django 4.2.5 on 2023-09-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/projects/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название проекта')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='описание проекта')),
                ('link', models.TextField(max_length=500, verbose_name='ссылка')),
                ('video', models.FileField(blank=True, default='', null=True, upload_to='videos/projects/', verbose_name='видео')),
                ('first_title_image', models.ImageField(default='', upload_to='images/title_images/', verbose_name='обязательно титульное изображение')),
                ('second_title_image', models.ImageField(blank=True, default='', null=True, upload_to='images/title_images/', verbose_name='титульное изображение')),
                ('third_title_image', models.ImageField(blank=True, default='', null=True, upload_to='images/title_images/', verbose_name='титульное изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_category', to='projects.categories', verbose_name='категория')),
                ('images', models.ManyToManyField(blank=True, to='projects.images', verbose_name='изображения')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ('id',),
            },
        ),
    ]
